---
# Installing pre-requistes
- name: Update Pip
  shell: pip install --upgrade pip

- name: Installing Azure CommandLine
  shell: yum install -y https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.5.1-1.el7.x86_64.rpm
  become: true
# Creating a file.
- name: Creating root directory
  file:
    path: /root/.azure
    state: directory
    mode: u+rwx,g+rwx,o+rx

- name: Create azure profile
  file:
    path: /root/.azure/azureProfile.json
    state: touch
    mode: u+rw,g+rw,o+r

# This will call the jenkins yaml file
- include_tasks: jenkins.yml
